name: Run Playwright Automation

on:
  schedule:
    # Queue ~30 minutes early to work around GitHub’s ±30‑minute cron delay
    - cron: '30 10,14,15,19 * * 1-5'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      EMPLOYER_CODE: ${{ secrets.EMPLOYER_CODE }}
      PIN:           ${{ secrets.PIN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sleep until next top‑of‑hour (UTC)
        run: |
          NOW=$(date +%s)
          TARGET=$(date -d "$(date -u +'%Y-%m-%d %H:00 UTC') +1 hour" +%s)
          DELAY=$((TARGET - NOW))
          if [ $DELAY -gt 0 ]; then
            echo "Sleeping $DELAY seconds until $(date -d @$TARGET -u)"
            sleep $DELAY
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chromium

      - name: Run Playwright test
        run: npx playwright test
